---
# tasks file for app_deploy
- name: Get list of services
  service_facts:

- name: Stop service, if exists
  ansible.builtin.systemd:
    name: instahelper.service
    state: stopped
  when: "'instahelper.service' in services"

- name: Create instahelper systemd service file
  template:
    src: templates/service.j2
    dest: /lib/systemd/system/instahelper.service

- name: Pull an image
  community.docker.docker_image:
    name: "{{ app_docker_image }}"
    source: pull

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    name: instahelper.service
    daemon_reload: true
    state: started

- name: Enable service
  ansible.builtin.systemd:
    name: instahelper.service
    enabled: true

- name: Copy file with tests
  ansible.builtin.copy:
    src: test.py
    dest: /tmp/
    mode: "0755"

- name: Start test
  ansible.builtin.command: pytest -v /tmp/test.py
  changed_when: false
